## Server Config ##
server:
  port: 80
  servlet:
    context-path: /dc

## Spring Config ##
spring:
  mvc:
    static-path-pattern: /**
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:/static/,classpath:/view/
